# permissions for end users to view climates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: temp-operator
    app.kubernetes.io/managed-by: kustomize
  name: climate-viewer-role
rules:
- apiGroups:
  - froystein.jp
  resources:
  - climates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - froystein.jp
  resources:
  - climates/status
  verbs:
  - get
