# permissions for end users to edit climates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: temp-operator
    app.kubernetes.io/managed-by: kustomize
  name: climate-editor-role
rules:
- apiGroups:
  - froystein.jp
  resources:
  - climates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - froystein.jp
  resources:
  - climates/status
  verbs:
  - get
