---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - froystein.jp
  resources:
  - climates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - froystein.jp
  resources:
  - climates/finalizers
  verbs:
  - update
- apiGroups:
  - froystein.jp
  resources:
  - climates/status
  verbs:
  - get
  - patch
  - update
