apiVersion: froystein.jp/v1
kind: Climate
metadata:
  labels:
    app.kubernetes.io/name: temp-operator
    app.kubernetes.io/managed-by: kustomize
  name: climate-sample
spec:
  # TODO(user): Add fields here
