name: Go

on:
  pull_request: {}

env:
  GO_VERSION: "1.22.5"
  GOLANGCI_VERSION: "v1.59.1"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
      - name: Setup Go environment
        uses: actions/setup-go@v5.0.1
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Build
        run: go build -v ./...

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
      - name: Setup Go environment
        uses: actions/setup-go@v5.0.1
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Test
        run: make test

  test-e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
      - name: Setup Go environment
        uses: actions/setup-go@v5.0.1
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Setup kind
        run: |
          go install sigs.k8s.io/kind@v0.23.0
          kind create cluster
      - name: Test E2E
        run: make test-e2e

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
      - name: Setup Go environment
        uses: actions/setup-go@v5.0.1
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v6.0.1
        with:
          version: ${{ env.GOLANGCI_VERSION }}
          args: --timeout=30m --config=.golangci.yml

  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - id: govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-version-input: ${{ env.GO_VERSION }}
          go-package: ./...

  gosec:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4.1.6
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
